Sehr <?php echo ($title == 'Herr') ? 'geehrter' : 'geehrte';?> <?php echo $title;?> <?php echo $lastname;?>,
<br/><br/>
Wir danken Ihnen für den Erwerb und die Einlösung Ihres DailyDeal-Gutscheines für eine wunderschöne SILVIO TOSSI
Handtasche zum Sonderpreis. Wir werden Ihre Angaben nun prüfen und das Produkt innert 7 Tagen versenden. Sollte es
Probleme mit Ihren Angaben geben, werden wir Sie umgehend kontaktieren.
<br/><br/>
Mit den besten Grüssen, Ihr SILVIO TOSSI Team

        