Sehr geehrter <?php echo ($title == 'Herr') ? 'geehrter' : 'geehrte';?> <?php echo $title;?> <?php echo $lastname;?>,
<br/><br/>
Vielen Dank für den Erwerb und die Einlösung Ihres DailyDeal-Gutscheins für Silvio Tossi.
<br/><br/>
Ihre Lieferdaten:
<br/><br/>
<?php echo $title;?> <?php echo $firstname;?> <?php echo $lastname;?><br/>
<?php echo $street;?> <?php echo $housenumber;?><br/>
<?php echo $postalcode;?> <?php echo $city;?>
<br/><br/>
<?php echo $email;?><br/>
<?php echo (strlen($telephone) > 0) ? $telephone . '<br/>' : '';?>
<?php echo ($newsletter == true) ? 'Newsletter: ja' : 'Newsletter: nein';?>

<br/><br/>
Ihr Gutschein-Code: <?php echo $vouchernumber;?>
<br/><br/>
<br/>
Wir werden Ihre Bestellung schnellst möglich bearbeiten.
<br/><br/>
Mit den besten Grüssen<br/>
Ihr SILVIO TOSSI Team


        