 <footer class="footer">
            <div class="row">
                <div class="span10">
                    <p class="footerLeftInner">
                        <a href="http://www.silviotossi.com">Silvio Tossi</a> |
                        <a href="http://www.twitter.com/silviotossi">Twitter</a> |
                        <a href="http://www.facebook.com/silviotossi">Facebook</a>
                        <?php
                        if (isset($_SESSION['loggedIn']) &&  $_SESSION['loggedIn'] == true) {
                            echo ' | <a href="/logout.php" style="color: red">Logout</a>';
                        }
                        ?>
                    </p>
                </div>
                <div class="span2">
                    <p class="footerRightInner">
                    &copy; silviotossi.com
                    </p>
                </div>
            </div>

        </footer>