<!--a.       Anrede
b.      Vorname
c.       Nachname
d.      Strasse
e.      Hausnummer
f.        PLZ
g.       Ort
h.      E-Mail-Adresse
i.         Gutscheinnummer
j.        Telefonnummer (optional aber empfohlen)-->
<div class="mod modForm">
<script type="text/javascript">
 var RecaptchaOptions = {
    lang : 'de',
    theme : 'white'

 };
 </script>
<form class="form-horizontal" method="post" action="/form-post.php">
    <fieldset>
        <legend>Lösen Sie Ihren Silvio Tossi Gutschein-Code ein.</legend>
        <div class="control-group">
            <label class="control-label" for="input00">Anrede</label>

            <div class="controls" autofocus>
                <select id="input00" name="title">
                    <option>Frau</option>
                    <option>Herr</option>
                </select>

                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">Vorname</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input01" name="firstname" required>

                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input03">Nachname</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input03" name="lastname" required>

                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input04">Strasse</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input04" name="street" required>

                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input05">Hausnummer</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input05" name="housenumber" required>

                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input06">PLZ</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input06" name="postalcode" required>

                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input07">Ort</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input07" name="city" required>

                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input08">E-Mail-Adresse</label>

            <div class="controls">
                <input type="email" class="input-xlarge" id="input08" name="email" required>

        
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input09">Gutscheinnummer</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input09" name="vouchernumber" required>

                <p class="help-block">z.B. 123 456 77</p>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input10">Telefon</label>

            <div class="controls">
                <input type="tel" class="input-xlarge" id="input10" name="telephone">

                <p class="help-block">+41 12 345 67 89 (Optional)</p>
            </div>
        </div>
<?php if ($ch->getEnvironmnent() != 'dev') {?>
        <div class="control-group">
            <label class="control-label">Sicherheit</label>
            <?php
          require_once('../application/libs/recaptchalib.php');
          $publickey = $ch->getConfig()->recaptcha_publickey;
          echo recaptcha_get_html($publickey);
        ?>
        </div>
<?php } ?>
        <div class="form-actions">
            <button class="btn btn-primary" type="submit">Absenden</button>
            <button class="btn" type="reset">Abbrechen</button>
          </div>
    </fieldset>
</form>

    </div>