<div class="mod modForm">
<script type="text/javascript">
 var RecaptchaOptions = {
    lang : 'de',
    theme : 'white'
 };
 </script>
<form class="form-horizontal" method="post" action="/form-post.php" novalidate>
    <fieldset>
        <legend>Lösen Sie Ihren Silvio Tossi Gutschein-Code ein</legend>
        <div class="control-group">
            <label class="control-label" for="input00">Anrede*</label>

            <div class="controls">
                <select id="input00" name="title" autofocus>
                    <option>Frau</option>
                    <option>Herr</option>
                </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input01">Vorname*</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input01" name="firstname" required>
                <span class="help-inline">Bitte geben Sie Ihren Vornamen ein.</span>
                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input03">Nachname*</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input03" name="lastname" required>
                <span class="help-inline">Bitte geben Sie Ihren Nachnamen ein.</span>
                
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input04">Strasse*</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input04" name="street" required>

                <span class="help-inline">Bitte geben Sie Ihre Strasse ein.</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input05">Hausnummer*</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input05" name="housenumber" required>

                <span class="help-inline">Bitte geben Sie Ihre Hausnummer ein.</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input06">PLZ*</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input06" name="postalcode" required>

                <span class="help-inline">Bitte geben Sie Ihre Postleitzahl ein.</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input07">Ort*</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input07" name="city" required>
                <span class="help-inline">Bitte geben Sie Ihre Stadt ein.</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input08">E-Mail-Adresse*</label>

            <div class="controls">
                <input type="email" class="input-xlarge" id="input08" name="email" required>

                <span class="help-inline">Bitte geben Sie Ihre E-Mail-Adresse ein.</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input09">Gutscheinnummer*</label>

            <div class="controls">
                <input type="text" class="input-xlarge" id="input09" name="vouchernumber" required>
                <button class="btn btn-small addVouchernumberInput" type="button">
                  Weitere Gutscheinnummer eingeben
                </button>
                <span class="help-inline">Bitte geben Sie eine gültige Gutscheinnummer ein.</span>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="input10">Telefon</label>

            <div class="controls">
                <input type="tel" class="input-xlarge" id="input10" name="telephone">   
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="optionsCheckboxList">Newsletter</label>
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" name="newsletter" value="true" id="optionsCheckboxList" checked>
                    Ja, bitte senden Sie mir regelmässig Newsletter
                </label>
            </div>
        </div>
<?php if ($ch->getEnvironmnent() != 'dev') {?>
        <div class="control-group">
            <label class="control-label">Sicherheit</label>
            <div class="controls">

            <?php
          require_once('../application/libs/recaptchalib.php');
          $publickey = $ch->getConfig()->recaptcha_publickey;
          echo recaptcha_get_html($publickey);
        ?>


            <span class="help-inline">Bitte geben Sie den korrekten Captcha-Code ein.</span>
            </div>
        </div>
<?php } ?>
        <div class="control-group">
            <label class="control-label"></label>
            <div class="controls">

            <p class="help-block"><strong>*</strong> Diese Felder sind pflicht.</p>
            </div>
        </div>



        <div class="form-actions">
            <button class="btn btn-primary" type="submit">Absenden</button>
            <button class="btn" type="reset">Abbrechen</button>
            <img class="ajaxLoader" src="/images/ajax-loader.gif" width="16" height="16" alt="" />
          </div>
    </fieldset>
    <input type="hidden" name="sess" value="<?php echo session_id();?>">
</form>

    </div>