<?php
$APPLICATION_ENVIRONMENT = getenv('APPLICATION_ENVIRONMENT');
if (strlen($APPLICATION_ENVIRONMENT) > 0 && $APPLICATION_ENVIRONMENT == 'prod') {
    ?>
?>
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-31194718-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>
<?php
}
?>