<!DOCTYPE html>
<html lang="de">
<head>
    <title><?php echo $lh->getLabel('TITLE');?> &ndash; <?php echo $page_title;?></title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link href="/images/favicon.ico" rel="shortcut icon">
    <link href="/stylesheets/bootstrap.min.css" media="all" rel="stylesheet" type="text/css">
    <link href="/stylesheets/base.css" media="all" rel="stylesheet" type="text/css">
</head>